GET https://869d-115-186-189-0.in.ngrok.io/api/parse/?url=https://www.militaryfactory.com/armor/pakistan-army-tanks.php HTTP/1.1

###
GET https://163f-203-175-72-61.ap.ngrok.io/api/parse/?url=https://www.carmax.com/cars HTTP/1.1

###
GET https://163f-203-175-72-61.ap.ngrok.io/api/parse/?url=https://www.wikipedia.com/ HTTP/1.1

###
GET https://kidstube.invotyx.com/api/parse/?url=https://www.dawn.com/ HTTP/1.1